import { mkdir, readFile, writeFile } from "node:fs/promises"
import { dirname, relative, resolve } from "node:path"
import * as ts from "typescript"

interface Procedure {
  name: string
  kind: "query" | "mutation"
  optimistic?: string
}

const projectRoot = resolve(import.meta.dirname, "..")
const sourceFile = resolve(projectRoot, "src/app/procedures.ts")
const clientFile = resolve(projectRoot, "src/generated/neon-realtime.ts")
const routesFile = resolve(projectRoot, "src/generated/routes.ts")

function fail(node: ts.Node, message: string): never {
  const { line, character } = node.getSourceFile().getLineAndCharacterOfPosition(node.getStart())
  throw new Error(`${relative(projectRoot, sourceFile)}:${line + 1}:${character + 1}: ${message}`)
}

function discover(source: ts.SourceFile): Procedure[] {
  const found: Procedure[] = []
  for (const statement of source.statements) {
    if (!ts.isVariableStatement(statement)) continue
    const exported = statement.modifiers?.some((item) => item.kind === ts.SyntaxKind.ExportKeyword)
    if (!exported) continue

    for (const declaration of statement.declarationList.declarations) {
      if (!ts.isIdentifier(declaration.name) || !declaration.initializer) continue
      const call = declaration.initializer
      if (!ts.isCallExpression(call) || !ts.isIdentifier(call.expression)) continue
      if (call.expression.text !== "defineQuery" && call.expression.text !== "defineMutation") continue
      const argument = call.arguments[0]
      if (call.arguments.length !== 1 || !argument || !ts.isObjectLiteralExpression(argument)) {
        fail(call, "procedure definitions must use one inline object literal")
      }

      const kind = call.expression.text === "defineQuery" ? "query" : "mutation"
      const config = argument
      if (kind === "query") {
        const query = config.properties.find(
          (property) =>
            (ts.isPropertyAssignment(property) || ts.isMethodDeclaration(property)) &&
            property.name.getText(source) === "query",
        )
        if (!query) fail(config, "defineQuery requires a query property")
        const implementation = ts.isPropertyAssignment(query) ? query.initializer : query
        if (
          ts.isPropertyAssignment(query) &&
          !ts.isArrowFunction(implementation) &&
          !ts.isFunctionExpression(implementation)
        ) {
          fail(implementation, "query must be an inline function")
        }
        const modifiers = ts.canHaveModifiers(implementation)
          ? ts.getModifiers(implementation)
          : undefined
        if (modifiers?.some((item) => item.kind === ts.SyntaxKind.AsyncKeyword)) {
          fail(implementation, "query must be synchronous so Drizzle does not execute before planning")
        }
        found.push({ name: declaration.name.text, kind })
        continue
      }

      const property = config.properties.find(
        (item): item is ts.PropertyAssignment =>
          ts.isPropertyAssignment(item) && item.name.getText(source) === "optimistic",
      )
      if (!property) fail(config, "defineMutation requires an optimistic property")
      if (!ts.isArrowFunction(property.initializer) && !ts.isFunctionExpression(property.initializer)) {
        fail(property.initializer, "optimistic must be an inline function")
      }
      found.push({
        name: declaration.name.text,
        kind,
        optimistic: property.initializer.getText(source),
      })
    }
  }
  return found
}

function renderClient(procedures: Procedure[]) {
  const entries = procedures.map((procedure) => {
    if (procedure.kind === "query") {
      return `export function ${procedure.name}(args: InferInput<typeof Procedures.${procedure.name}>) {\n  return getReactiveClient().query<RowsOf<InferOutput<typeof Procedures.${procedure.name}>>>("${procedure.name}", args)\n}`
    }
    return `export function ${procedure.name}(args: InferInput<typeof Procedures.${procedure.name}>) {\n  return getReactiveClient().mutate("${procedure.name}", args, ${procedure.optimistic})\n}`
  })

  return `// Generated by pnpm generate. Do not edit.\nimport { getReactiveClient } from "../runtime/client.js"\nimport type { InferInput, InferOutput } from "../core/definition.js"\nimport type * as Procedures from "../app/procedures.js"\n\ntype RowsOf<T> = T extends readonly (infer TRow extends Record<string, unknown>)[] ? TRow : never\n\n${entries.join("\n\n")}\n`
}

function renderRoutes(procedures: Procedure[]) {
  const entries = procedures.map(({ name }) => `  ${name}: Procedures.${name},`).join("\n")
  return `// Generated by pnpm generate. Do not edit.\nimport * as Procedures from "../app/procedures.js"\nimport { createNodeRouter } from "../runtime/server.js"\n\nexport const procedures = {\n${entries}\n}\n\nexport const reactiveNeonRouter = createNodeRouter(procedures)\n`
}

const text = await readFile(sourceFile, "utf8")
const source = ts.createSourceFile(sourceFile, text, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS)
const procedures = discover(source)
if (procedures.length === 0) throw new Error("No exported procedures found")

await mkdir(dirname(clientFile), { recursive: true })
await Promise.all([
  writeFile(clientFile, renderClient(procedures)),
  writeFile(routesFile, renderRoutes(procedures)),
])
console.log(`Generated ${procedures.length} procedures`)
